/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import project.UI.*;
import project.database.*;
import project.UI.*;
// import project.UI.AdminDisplay;
// import project.UI.Display;
// import project.UI.Preview;
import project.UI.LogInView;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        // Code for downloading files
//        DownloadHandler dh = new DownloadHandler();
//        dh.downloadFile("");

        // Code for previewing files
//        Preview p = new Preview();
//        p.previewFile("");

// Code for uploading files
//        UploadHandler uh = new UploadHandler();
//        uh.userUpload();
//        uh.uploadFile("C:/Users/mohit/Downloads/blah", "blah");


        //create the tables
        CreateTables.createCredsTable();
        CreateTables.createScrollsTable();
        CreateTables.createTotalDownloads();
        CreateTables.createTotalUpdates();

        PopulateTables.populateCredentials();
        PopulateTables.populateScrolls();

////        SelectRecords.selectAllFromTotalDownloads();
//        System.out.println();


//                code for scroll of the day
        ScrollOfTheDay sd = new ScrollOfTheDay();
        sd.printScroll();
        System.out.println();

//
        SelectRecords.selectAllFromCreds(); //just for reference
        System.out.println("\n\n\n");
        SelectRecords.selectAllFromScrolls();
        System.out.println("\n\n\n");
        SelectRecords.selectAllFromTotalDownloads();
        System.out.println("\n\n\n");
        SelectRecords.selectAllFromTotalUpdates();
        System.out.println("\n\n\n");
        SelectRecords.selectAllFromTotalUpdates();
        System.out.println();

        // code for scroll of the day
//        ScrollOfTheDay sd = new ScrollOfTheDay();
//
//        sd.printScroll();

        LogInView login = new LogInView();
        login.main();

    }
}
